source: [src]

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: [Welcome!]
description: [A short description of your site's purpose]

# theme: jekyll-theme-THEME-NAME
# show_downloads: ["true" or "false" (unquoted) to indicate whether to provide a download URL]
# google_analytics: [Your Google Analytics tracking ID]